(() => {
'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={records:[],fields:[],profile:{},api:{},config:{},diagnostics:{}},route='dashboard',patientId='',visitId='',tab='history',settingsTab='general',dirty=false;
const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const labels={approved:'Aprobado',pending:'Pendiente',pending_review:'Pendiente de revisión',reviewed:'Revisada',rejected:'Rechazado',draft:'Borrador',closed:'Cerrada',stored:'Original guardado',queued:'En cola',transcribing:'Transcribiendo',transcribed:'Transcrita',extracted:'OCR pendiente de revisión',superseded:'Versión anterior',completed:'Completada',failed:'Fallida'};
const origins={measured:'Medición',reported:'Referido',document:'Documentado',ocr:'Extraído por OCR'};
const avail={not_evaluated:'No evaluado',present:'Dato registrado',none_reported:'Ninguno referido',unknown:'Desconocido',not_applicable:'No aplica'};
function list(kind,p){return state.records.filter(r=>r.kind===kind&&(!p||r.patient===p))}function record(id){return state.records.find(r=>r.id===id)}
function currentPatient(){return record(patientId)}function currentVisit(){return record(visitId)}
function dateToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmtDate(s){if(!s)return 'Sin fecha';const d=new Date(s.length===10?s+'T12:00:00':s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})}
function initials(name){return name.split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase()}
function status(s){return `<span class="tag ${s==='approved'||s==='completed'?'good':s==='rejected'||s==='failed'?'bad':s==='pending'||s==='draft'?'warn':''}">${esc(labels[s]||s)}</span>`}
function button(label,action,id='',cls=''){return `<button type="button" class="${cls}" data-action="${action}" data-id="${esc(id)}">${esc(label)}</button>`}
function options(items,value){return items.map(item=>{let [v,label]=Array.isArray(item)?item:[item,item];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(label)}</option>`}).join('')}
function field(label,name,value='',type='text',extra=''){return `<label class="field">${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function area(label,name,value='',extra=''){return `<label class="field">${esc(label)}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`}
function select(label,name,items,value=''){return `<label class="field">${esc(label)}<select name="${name}">${options(items,value)}</select></label>`}
function check(label,name){return `<label class="check"><input name="${name}" type="checkbox"><span>${esc(label)}</span></label>`}
function empty(title,description,action=''){return `<div class="empty"><div class="empty-icon">＋</div><h3>${esc(title)}</h3><p>${esc(description)}</p>${action}</div>`}
function heading(title,desc,actions=''){return `<div class="heading"><div><div class="eyebrow">Consulta local · Nutrición clínica</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),5500)}
async function api(path,data,blob=false){if(window.supabaseCloud&&location.hostname.endsWith('github.io'))return window.supabaseCloud.api(path,data,blob);const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':state.csrf||''}:{},body:data?JSON.stringify(data):undefined});if(!r.ok){let e;try{e=await r.json()}catch{e={error:'No se pudo completar la solicitud.'}}if(r.status===401)await boot();throw Error(e.error)}return blob?r.blob():r.json()}
async function refresh(){state=await api('state');if(patientId&&!record(patientId))patientId='';if(patientId){let visits=list('visit',patientId);if(!visitId||!visits.some(v=>v.id===visitId))visitId=visits[0]?.id||''}render()}
function guard(){if(dirty&&!confirm('Hay cambios sin guardar. ¿Quieres descartarlos?'))return false;dirty=false;return true}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
function modal(title,body,onSubmit,submit='Guardar'){
 $('modal-content').innerHTML=`<form id="modal-form"><div class="modal-head"><h2>${esc(title)}</h2><button type="button" data-action="close-modal" aria-label="Cerrar">✕</button></div><div class="modal-body">${body}<div id="modal-error" class="form-error" role="alert"></div></div><div class="modal-footer"><button type="button" data-action="close-modal">Cancelar</button><button class="primary" type="submit">${esc(submit)}</button></div></form>`;
 $('modal').showModal();$('modal-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const btn=form.querySelector('button[type=submit]');btn.disabled=true;$('modal-error').textContent='';try{await onSubmit(new FormData(form),form);$('modal').close();await refresh()}catch(ex){$('modal-error').textContent=ex.message}finally{btn.disabled=false}});
}
function readonlyModal(title,body){$('modal-content').innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button type="button" data-action="close-modal" aria-label="Cerrar">✕</button></div><div class="modal-body">${body}</div>`;$('modal').showModal()}
async function boot(){try{const b=await api('bootstrap');if(!b.authenticated){auth(b.configured);return}await refresh()}catch(e){$('app').innerHTML=empty('No se pudo abrir la aplicación',e.message,button('Reintentar','boot'))}}
function auth(configured){const cloud=!!(window.supabaseCloud&&location.hostname.endsWith('github.io'));$('app').innerHTML=`<div class="auth"><div class="auth-left"><div class="eyebrow">Nutrición clínica · ${cloud?'Supabase':'Espacio local'}</div><h1>Tu consulta, con cada dato en su lugar.</h1><p>Expediente, estudios y planes de alimentación conectados.</p><div class="auth-list"><span>01 &nbsp; Datos con origen y revisión</span><span>02 &nbsp; Seguimiento entre consultas</span><span>03 &nbsp; Planes con versión y aprobación</span></div></div><div class="auth-right"><form id="auth-form" class="auth-form"><h2>Bienvenido de nuevo</h2><p>${cloud?'Acceso profesional con Supabase Auth.':'Introduce tu contraseña local para abrir los expedientes.'}</p>${field(cloud?'Contraseña de Supabase':'Contraseña local','password','','password','required autocomplete="current-password"')}<div class="form-error" id="auth-error" role="alert"></div><button class="primary" type="submit">Abrir mi consulta</button><p class="tiny muted">${cloud?'Usuario: dannapyn@nutricion.com · conexión cifrada con Supabase.':'La contraseña protege el acceso local.'}</p></form></div></div>`;$('auth-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await api('login',Object.fromEntries(f));await refresh()}catch(ex){$('auth-error').textContent=ex.message}finally{btn.disabled=false}}}
function render(){const pages=[['dashboard','Resumen'],['patients','Expedientes'],['studies','Estudios'],['plans','Planes'],['foods','Alimentos'],['sources','Fuentes'],['settings','Ajustes']];let name=state.profile.name||'Profesional';$('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">NUTRICIÓN<span>CLÍNICA · ${state.cloud?'SUPABASE':'LOCAL'}</span></div><div class="side-label">Espacio de consulta</div><nav class="nav">${pages.map(([r,l],i)=>`<button type="button" data-action="route" data-id="${r}" class="${route===r||(route==='patient'&&r==='patients')?'active':''}"><span class="nav-num">0${i+1}</span>${l}</button>`).join('')}</nav><div class="sidebar-bottom"><span class="status-dot"></span>${state.cloud?'Datos protegidos en Supabase':'Datos en esta computadora'}<br>v${esc(state.version)} · ${state.cloud?'Vista remota inicial':'Primera versión funcional'}<br><br>OCR e IA: ${state.api.enabled&&state.api.key_available?'configurados':'por configurar'}</div></aside><div class="workspace"><header class="topbar"><span class="breadcrumb">Mi consulta &nbsp; / &nbsp; ${esc(route==='patient'?currentPatient()?.name||'Expediente':pages.find(p=>p[0]===route)?.[1]||'Resumen')}</span><div class="profile"><span class="avatar">${esc(initials(name))}</span><span class="name">${esc(name)}</span>${button('Salir','logout','','ghost')}</div></header><main class="content" id="content"></main></div></div>`;
 const views={dashboard:dashboard,patients:patients,patient:patient,studies:studies,plans:plans,foods:foods,sources:sources,settings:settings};$('content').innerHTML=(state.test_mode?'<div class="test-banner"><strong>MODO DE PRUEBA</strong> · Usa exclusivamente nombres, estudios y datos ficticios. Las funciones activas guardan información en Supabase.</div>':'')+views[route]();wireView();}
function dashboard(){const pts=list('patient'),pending=list('observation').filter(o=>o.status==='pending'),drafts=list('plan').filter(p=>p.status==='draft');return heading('Panorama de tu consulta','Información pendiente, evolución y próximos pasos.',button('Nuevo expediente','new-patient','','primary'))+`<div class="cards"><div class="card"><div class="label">Expedientes</div><div class="value">${pts.length}</div><div class="detail">Personas registradas en este espacio</div></div><div class="card"><div class="label">Datos por revisar</div><div class="value">${pending.length}</div><div class="detail">Pendientes antes de uso clínico</div></div><div class="card"><div class="label">Planes en borrador</div><div class="value">${drafts.length}</div><div class="detail">Aún no entregados al paciente</div></div></div>`+(!pts.length?empty('Tu primer expediente comienza aquí','Crea un expediente para registrar la primera consulta. Puedes usar un nombre ficticio para probar el recorrido.',button('Crear expediente','new-patient','','primary')):`<div class="grid2"><section class="panel"><div class="panel-head"><h2>Expedientes recientes</h2>${button('Ver todos','route','patients','ghost')}</div>${patientTable(pts.slice(0,6))}</section><section class="panel"><div class="panel-head"><h2>Revisión pendiente</h2>${status('pending')}</div>${pending.length?pending.slice(0,6).map(o=>`<div class="entry"><div class="entry-title"><strong>${esc(o.label)} · ${esc(o.value)} ${esc(o.unit)}</strong>${button('Revisar','review-observation',o.id)}</div><span class="small muted">${esc(record(o.patient)?.name)} · ${esc(o.source)}</span></div>`).join(''):'<p class="muted small">No hay datos pendientes de validación.</p>'}</section></div>`)+`<section class="panel with-gap"><div class="panel-head"><h2>Preparación del espacio</h2></div><div class="grid3"><div><h3>Fuentes clínicas</h3><p class="small muted">${list('source').filter(s=>s.status==='approved').length} de ${list('source').length} fuentes revisadas por el profesional.</p>${button('Revisar fuentes','route','sources')}</div><div><h3>Procesamiento externo</h3><p class="small muted">${state.api.key_available?'Credencial disponible.':'No se ha configurado una clave API.'} Cada envío requiere confirmación en la aplicación.</p>${button('Configurar API','route','settings')}</div><div><h3>Respaldo</h3><p class="small muted">Descarga una copia cifrada del expediente y sus documentos. La contraseña del respaldo es independiente.</p>${button('Crear respaldo','backup')}</div></div></section>`}
function patientTable(pts){return table(['Paciente','Consulta reciente',''],pts.map(p=>{let vs=list('visit',p.id);return `<tr><td><strong>${esc(p.name)}</strong><span class="small muted">${p.dob?fmtDate(p.dob):'Nacimiento no registrado'} ${p.demo?'· Ficticio':''}</span></td><td>${fmtDate(vs[0]?.date)}<div class="tags">${p.modules.map(m=>`<span class="tag">${esc(m)}</span>`).join('')}</div></td><td>${button('Abrir','open-patient',p.id)}</td></tr>`}))}
function patients(){let pts=list('patient');return heading('Expedientes','Historia, estudios y seguimiento en un solo lugar.',button('Nuevo expediente','new-patient','','primary'))+`<div class="toolbar"><label class="field">Buscar paciente<input id="patient-search" type="search" placeholder="Nombre o identificador"></label></div><div class="panel" id="patient-results">${pts.length?patientTable(pts):empty('No hay expedientes','Crea el primero para comenzar.')}</div>`}
function patient(){const p=currentPatient();if(!p)return empty('Selecciona un expediente','Abre uno desde la lista de pacientes.',button('Ver expedientes','route','patients'));let visits=list('visit',p.id),v=currentVisit();return `<div class="heading"><div class="patient-header"><div class="avatar">${esc(initials(p.name))}</div><div><div class="eyebrow">Expediente ${p.id.slice(0,8)} ${p.demo?'· Ficticio':''}</div><h1>${esc(p.name)}</h1><p>${p.dob?fmtDate(p.dob):'Nacimiento no registrado'} · ${p.modules.map(esc).join(' / ')||'Sin módulos seleccionados'}</p></div></div><div class="actions">${button('Nueva consulta','new-visit',p.id,'primary')}${button('Historial','audit',p.id)}</div></div>`+(!v?empty('Registra la primera consulta','Elige la fecha y el motivo; podrás completar la historia progresivamente.',button('Crear consulta','new-visit',p.id,'primary')):`<div class="toolbar"><label class="field visit-selector">Consulta<select id="visit-select">${options(visits.map(x=>[x.id,fmtDate(x.date)+' · '+x.reason]),visitId)}</select></label><div class="field">${status(v.status)}</div>${button('Historial de consulta','audit',v.id,'ghost')}</div><nav class="tabs">${[['history','Historia clínica'],['audio','Audio y transcripción'],['observations','Mediciones'],['documents','Estudios'],['evaluation','Evaluación'],['menu','Plan alimentario'],['evolution','Evolución']].map(([id,label])=>button(label,'patient-tab',id,tab===id?'active':'')).join('')}</nav>${({history:historyView,audio:audioView,observations:observationsView,documents:documentsView,evaluation:evaluationView,menu:menuView,evolution:evolutionView})[tab](v)}`)}
function audioView(v){const audios=list('recording',patientId).filter(a=>a.visit===v.id);return `<div class="grid2"><section class="panel"><div class="panel-head"><div><h2>Audio de esta consulta</h2><p class="small muted">Original privado · consentimiento obligatorio · máximo 50 MB</p></div>${v.status==='draft'?button('Subir grabación','upload-audio',v.id,'primary'):''}</div>${audios.length?audios.map(a=>{const t=list('transcript').find(x=>x.recording===a.id);return `<div class="entry"><div class="entry-title"><div><strong>${esc(a.original_name)}</strong><p class="small muted">${fmtDate(a.recorded_at||a.created)} · ${(a.size_bytes/1048576).toFixed(1)} MB</p></div>${status(a.status)}</div><p class="tiny muted">SHA-256: ${esc(a.sha256)}</p>${t?`<div class="notice ${t.status==='reviewed'?'':'info'}"><div class="entry-title"><strong>Transcripción ${status(t.status)}</strong>${button(t.status==='pending_review'?'Revisar texto':'Consultar revisión','review-transcript',t.id)}</div><p class="pre transcript-preview">${esc(t.text||'Sin texto reconocido.')}</p></div>`:a.status==='failed'?'<p class="form-error">No se pudo transcribir. El audio original permanece guardado.</p>':'<p class="small muted">La transcripción se está preparando. Actualiza la página en unos momentos.</p>'}</div>`}).join(''):empty('Todavía no hay grabaciones','Carga el audio de una consulta ficticia para probar la transcripción.')}</section><section class="panel"><h2>Flujo de revisión</h2><ol class="clean"><li>Documentar consentimiento y finalidad.</li><li>Conservar el audio original con huella SHA-256.</li><li>Transcribir en español y separar hablantes.</li><li>Revisar la transcripción contra el audio.</li><li>Promover datos concretos al expediente con fuente y fecha.</li></ol><p class="small muted">La transcripción aporta contexto y puede contener errores. Solo se considera revisada cuando el profesional registra su decisión.</p></section></div>`}
function historyView(v){let groups={};state.fields.forEach(f=>(groups[f.module]??=[]).push(f));return `<form id="history-form"><div class="panel"><div class="panel-head"><div><h2>${esc(v.type)} · ${fmtDate(v.date)}</h2><p class="muted small">${esc(v.reason)}</p></div>${status(v.status)}</div><div class="notice info">Completa lo pertinente. “No evaluado” se conserva como tal y no equivale a una respuesta negativa.</div></div>${Object.entries(groups).map(([module,fields],i)=>`<details class="module" ${i===0?'open':''}><summary>${esc(module)} <span class="tag">${fields.filter(f=>v.history[f.id]?.availability&&v.history[f.id].availability!=='not_evaluated').length}/${fields.length}</span></summary><div class="module-body">${fields.map(f=>{const val=v.history[f.id]||{};return `<div class="history-field"><strong>${esc(f.label)}</strong><div class="history-inputs">${select('Estado',f.id+'_availability',Object.entries(avail),val.availability||'not_evaluated')}${area('Dato registrado',f.id+'_value',val.value||'')}<label class="field source">Fuente / quién lo refiere<input name="${f.id}_source" value="${esc(val.source||'Paciente, registrado por profesional')}"><small>${esc(f.rule)}</small></label></div></div>`}).join('')}</div></details>`).join('')}<div class="panel with-gap">${area('Valoración profesional', 'assessment',v.assessment||'')}${area('Objetivos acordados y forma de seguimiento','goals',v.goals||'')}${field('Próxima revisión (opcional)','next_date',v.next_date||'','date')}</div>${v.status==='draft'?`<div class="savebar">${button('Cerrar consulta','close-visit',v.id)}<button class="primary" type="submit">Guardar historia</button></div>`:'<div class="notice">Consulta cerrada. Su contenido se conserva; abre un seguimiento para nuevos datos.</div>'}</form>`}
function obsTable(items){return table(['Dato','Valor original','Origen y fecha','Estado',''],items.map(o=>`<tr><td><strong>${esc(o.label)}</strong><span class="small muted">${esc(o.method)}</span></td><td>${esc(o.value)} ${esc(o.unit)}<br><span class="small muted">${esc(o.reference)}</span></td><td>${esc(origins[o.origin]||o.origin)}<br><span class="small muted">${fmtDate(o.date)} · ${esc(o.source)}</span></td><td>${status(o.status)}</td><td><div class="actions">${button(o.status==='pending'?'Revisar':'Rectificar','review-observation',o.id)}${button('Origen','audit',o.id,'ghost')}</div></td></tr>`))}
function observationsView(v){let items=list('observation',patientId).filter(o=>o.visit===v.id);return `<section class="panel"><div class="panel-head"><div><h2>Mediciones y resultados</h2><p class="small muted">Cada observación conserva método, fecha, fuente y revisión.</p></div>${v.status==='draft'?button('Registrar dato','new-observation',v.id,'primary'):''}</div>${items.length?obsTable(items):empty('Sin observaciones','Registra medidas o carga un estudio para extraer resultados.')}</section>`}
function documentsList(docs){return docs.map(d=>`<div class="entry"><div class="entry-title"><div><strong>${esc(d.name)}</strong><p class="small muted">${esc(d.study_type)} · ${fmtDate(d.date)} · ${(d.size/1024).toFixed(0)} KB</p></div><div class="actions">${button('Abrir original','open-document',d.id)}${button('Cotejar identidad','identity',d.id)}${button('Extraer con OCR','ocr',d.id,'primary')}</div></div><div class="tags">${status(d.status)}<span class="tag ${d.identity_verified?'good':'warn'}">${d.identity_verified?'Identidad cotejada':'Identidad por confirmar'}</span></div>${d.ocr_notes?`<p class="small muted">${esc(d.ocr_notes)}</p>`:''}</div>`).join('')}
function documentsView(v){const docs=list('document',patientId).filter(d=>d.visit===v.id);return `<section class="panel"><div class="panel-head"><div><h2>Estudios de esta consulta</h2><p class="muted small">PDF, PNG o JPEG · hasta 15 MB · original conservado</p></div>${v.status==='draft'?button('Subir estudio','upload',v.id,'primary'):''}</div>${docs.length?documentsList(docs):empty('Agrega un informe de laboratorio o estudio','Los resultados extraídos quedarán pendientes hasta que los revises.')}</section>`}
function studies(){const docs=list('document');return heading('Estudios','Originales y resultados pendientes, organizados por expediente.')+`<section class="panel">${docs.length?docs.map(d=>`<h3 class="with-gap">${esc(record(d.patient)?.name)}</h3>${documentsList([d])}`).join(''):empty('No hay estudios cargados','Abre una consulta para vincular cada estudio a su paciente.',button('Abrir expedientes','route','patients'))}</section>`}
function evaluationView(v){const calcs=list('calculation',patientId).filter(c=>c.visit===v.id&&c.status!=='superseded'),proposals=list('proposal',patientId).filter(p=>p.visit===v.id);return `<section class="panel"><div class="panel-head"><div><h2>Cálculos documentados</h2><p class="small muted">Las estimaciones no se convierten automáticamente en prescripciones.</p></div>${v.status==='draft'?button('Nuevo cálculo','calculate',v.id,'primary'):''}</div>${calcs.length?`<div class="grid2">${calcs.map(c=>`<div class="card"><div class="tags"><span class="tag">${c.formula==='bmi'?'IMC':'Gasto en reposo'}</span>${c.stale?'<span class="tag warn">Desactualizado</span>':status('approved')}</div><p class="metric-value">${esc(c.value)} <span class="small muted">${esc(c.unit)}</span></p><p class="small muted">${esc(c.source_snapshot.formula)}</p>${button('Ver entradas y fuente','calc-detail',c.id)}</div>`).join('')}</div>`:empty('Aún no hay cálculos','Aprueba la fuente y selecciona observaciones validadas para obtener un resultado reproducible.')}</section><section class="panel"><div class="panel-head"><div><h2>Asistencia de IA</h2><p class="small muted">Borradores con contexto y fuentes; revisión profesional obligatoria.</p></div>${v.status==='draft'?button('Solicitar borrador','ai',v.id):''}</div>${proposals.length?proposals.map(p=>`<div class="entry"><div class="entry-title"><h3>${esc(p.task)}</h3>${status(p.status)}</div><p class="pre">${esc(p.text)}</p>${p.missing.length?`<p class="small muted">Faltantes: ${p.missing.map(esc).join('; ')}</p>`:''}<p class="small">Fuentes: ${p.source_ids.map(id=>`<a href="${esc(record(id)?.url||'#')}" target="_blank" rel="noopener noreferrer">${esc(record(id)?.title||id)}</a>`).join(' · ')}</p>${p.status==='pending'?button('Revisar propuesta','review-proposal',p.id):''}</div>`).join(''):'<p class="muted small">No se han enviado datos clínicos para generar propuestas en esta consulta.</p>'}</section>`}
function planTotals(p){const totals=days.map(()=>({kcal:0,protein:0,carbs:0,fat:0,items:0,complete:true}));for(const i of p.items){const d=totals[i.day];d.items++;for(const k of ['kcal','protein','carbs','fat']){if(i.nutrients[k]===null||i.nutrients[k]===undefined||i.nutrients[k]==='')d.complete=false;else d[k]+=Number(i.nutrients[k])}if(!i.nutrition_source)d.complete=false}return totals}
function planCard(p){const t=planTotals(p);return `<div class="entry"><div class="entry-title"><div><h3>${esc(p.title)} <span class="tag">v${p.version}</span></h3><p class="small muted">${esc(record(p.patient)?.name)} · ${fmtDate(p.created)}</p></div><div class="tags">${status(p.status)}${p.stale?'<span class="tag warn">Entradas modificadas después de aprobación</span>':''}</div></div><p>${esc(p.objective)}</p><div class="actions">${p.status==='draft'?button('Editar','edit-plan',p.id)+button('Revisar y aprobar','approve-plan',p.id,'primary'):`<a href="/api/pdf/${p.id}" target="_blank" rel="noopener">Descargar PDF</a> ${button('Nueva versión','clone-plan',p.id)}`}${button('Ver contenido','preview-plan',p.id)}${button('Historial','audit',p.id,'ghost')}</div><p class="small muted">${p.items.length} preparaciones · ${t.filter(d=>d.items).length} días con contenido · ${t.filter(d=>d.items&&!d.complete).length} días con totales incompletos</p></div>`}
function menuView(v){let items=list('plan',patientId).filter(p=>p.visit===v.id);return `<section class="panel"><div class="panel-head"><div><h2>Plan alimentario</h2><p class="small muted">Edición manual o propuesta de IA para revisar. Documento interno y PDF comparten versión.</p></div>${v.status==='draft'?button('Crear plan','new-plan',v.id,'primary'):''}</div>${items.length?items.map(planCard).join(''):empty('Organiza la intervención de esta consulta','Comienza con los objetivos y añade preparaciones por día.')}</section>`}
function plans(){let all=list('plan');return heading('Planes alimentarios','Borradores, versiones aprobadas y documentos para el paciente.')+`<section class="panel">${all.length?all.map(planCard).join(''):empty('No hay planes todavía','Crea un plan dentro de una consulta.',button('Abrir expedientes','route','patients'))}</section>`}
function evolutionView(){let obs=list('observation',patientId).filter(o=>o.status==='approved'&&o.date).sort((a,b)=>a.date.localeCompare(b.date));let weights=obs.filter(o=>o.label==='Peso'&&o.unit==='kg'&&Number.isFinite(Number(o.value))),methods=[...new Set(weights.map(o=>o.method))],chart='';if(weights.length>1&&methods.length===1){let min=Math.min(...weights.map(o=>Number(o.value)))-1,max=Math.max(...weights.map(o=>Number(o.value)))+1;const x=i=>55+i/(weights.length-1)*520,y=n=>185-(n-min)/(max-min)*145;chart=`<svg class="report-figure" viewBox="0 0 630 235" role="img" aria-label="Evolución de peso con el mismo método"><line x1="55" y1="185" x2="575" y2="185" stroke="#c6d4dc"/><polyline points="${weights.map((o,i)=>`${x(i)},${y(Number(o.value))}`).join(' ')}" fill="none" stroke="#087c72" stroke-width="2"/>${weights.map((o,i)=>`<circle cx="${x(i)}" cy="${y(Number(o.value))}" r="4" fill="#087c72"/><text x="${x(i)}" y="${y(Number(o.value))-12}" text-anchor="middle">${esc(o.value)} kg</text>${(i===0||i===weights.length-1)?`<text x="${x(i)}" y="210" text-anchor="middle">${esc(o.date)}</text>`:''}`).join('')}<text x="20" y="24">Peso (kg) · secuencia de mediciones</text></svg>`}
 const grouped={};obs.forEach(o=>(grouped[o.label]??=[]).push(o));const longitudinal=Object.entries(grouped).flatMap(([label,values])=>values.map((o,i)=>{const prev=values[i-1],comparable=prev&&o.unit===prev.unit&&o.method===prev.method&&Number.isFinite(Number(o.value))&&Number.isFinite(Number(prev.value)),delta=comparable?Number(o.value)-Number(prev.value):null;return `<tr><td><strong>${esc(label)}</strong></td><td>${fmtDate(o.date)}</td><td><strong>${esc(o.value)} ${esc(o.unit)}</strong></td><td>${esc(o.reference_low!==''&&o.reference_low!=null&&o.reference_high!==''&&o.reference_high!=null?`${o.reference_low}–${o.reference_high} ${o.unit}`:o.reference||'No registrado')}</td><td>${esc(o.method)}</td><td>${delta===null?(prev?'No comparable':'Inicial'):`${delta>0?'+':''}${Math.round(delta*100)/100} ${esc(o.unit)}`}</td><td>${button('Trazabilidad','audit',o.id,'ghost')}</td></tr>`}));
 return `<section class="panel"><div class="panel-head"><div><h2>Valores longitudinales</h2><p class="small muted">Resultados aprobados ordenados por fecha. “Cambio” es una diferencia matemática, no una interpretación clínica.</p></div>${button('Analizar datos aprobados con IA','ai',visitId)}</div>${longitudinal.length?table(['Indicador','Fecha','Resultado','Referencia impresa','Método / laboratorio','Cambio comparable','Origen'],longitudinal):empty('Sin datos longitudinales','Registra o extrae resultados de estudios y apruébalos para construir esta tabla.')}</section><section class="panel"><h2>Evolución de peso</h2>${chart||`<p class="muted">${methods.length>1?'Hay métodos diferentes: los datos se muestran sin unirlos como una tendencia comparable.':'Registra al menos dos pesos aprobados y fechados con el mismo método.'}</p>`}</section><section class="panel"><h2>Consultas y decisiones</h2><div class="timeline with-gap">${list('visit',patientId).map(v=>`<div class="timeline-item"><strong>${fmtDate(v.date)} · ${esc(v.reason)}</strong><p class="pre">${esc(v.assessment||'Valoración aún no registrada.')}</p><span class="small muted">${esc(v.goals||'Objetivos pendientes')}</span></div>`).join('')}</div></section>`}
function sources(){return heading('Fuentes y métodos','Referencias verificadas técnicamente; su aplicación clínica requiere tu revisión.',button('Añadir fuente','new-source','','primary'))+`<div class="notice info">El catálogo inicial contiene dos métodos de cálculo. Las guías específicas de tiroides, menopausia y alteraciones metabólicas aún no están activadas como reglas clínicas.</div>${list('source').map(s=>`<section class="panel"><div class="panel-head"><h2>${esc(s.title)}</h2>${status(s.status)}</div><p>${esc(s.summary)}</p><div class="source-formula">${esc(s.formula)}</div><p class="small muted">${esc(s.scope)}<br>Versión: ${esc(s.version)} · Consulta documental: ${s.reviewed_at}</p><div class="actions"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Abrir fuente original ↗</a>${button(s.status==='approved'?'Revisar estado':'Registrar revisión','review-source',s.id)}</div>${s.approved_by?`<p class="small muted">Revisión: ${esc(s.approved_by)} · ${fmtDate(s.approved_at)} · ${esc(s.review_note)}</p>`:''}</section>`).join('')}`}

function foods(){return heading('Catálogo de alimentos','Composición por 100 g, con fuente y estado crudo/cocido.',button('Añadir alimento','new-food','','primary'))+`<section class="panel"><p class="small muted">No hay valores nutricionales precargados sin fuente. Registra la composición documentada y úsala en preparaciones calculadas.</p>${list('food').length?table(['Alimento / estado','Energía','P / HC / G','Fuente'],list('food').map(f=>`<tr><td><strong>${esc(f.name)}</strong>${esc(f.state)}</td><td>${f.nutrients.kcal} kcal</td><td>${f.nutrients.protein} / ${f.nutrients.carbs} / ${f.nutrients.fat} g</td><td>${esc(f.source)}</td></tr>`)):empty('Tu catálogo aún está vacío','Añade alimentos desde una etiqueta, tabla o fuente que puedas revisar. No se asumen nutrientes faltantes.')}</section>`}
function newFood(){modal('Añadir composición verificada',field('Alimento y marca, si aplica','name','','text','required')+field('Estado del alimento','state','','text','required placeholder="Crudo, cocido, producto tal como se vende…"')+`<p class="small muted">Todos los valores se expresan por 100 g del alimento en el estado indicado.</p><div class="grid2">${field('Energía (kcal)','kcal','','number','required min="0" step="any"')}${field('Proteína (g)','protein','','number','required min="0" step="any"')}${field('Hidratos de carbono (g)','carbs','','number','required min="0" step="any"')}${field('Grasa (g)','fat','','number','required min="0" step="any"')}</div>`+area('Fuente, versión y ubicación del dato','source','','required')+check('Revisé estos datos contra la fuente indicada','confirmed'),async f=>{await api('foods',{...Object.fromEntries(f),confirmed:f.has('confirmed')})},'Guardar alimento')}
function newSource(){modal('Añadir fuente al catálogo',field('Título','title','','text','required')+field('URL original','url','','url','required')+field('Versión / fecha','version','','text','required')+area('Contenido comprobado que respaldará las propuestas','summary','','required')+area('Población, alcance y límites','scope','','required'),async f=>{await api('sources',Object.fromEntries(f))},'Guardar para revisión')}

function settings(){const tabs=[['general','Consulta'],['clinical','Seguridad clínica'],['api','API y OCR'],['documents','Documentos y PDF'],['security','Acceso y respaldo'],['system','Sistema']];const c=state.config||{},clinical=c.clinical||{},docs=c.documents||{},pdf=c.pdf||{},security=c.security||{},backupCfg=c.backup||{},d=state.diagnostics||{},ops=list('operation');let body='';
 if(settingsTab==='general')body=`<section class="panel"><h2>Identidad de la consulta</h2><p class="small muted">Estos datos identifican al responsable y pueden presentarse en los documentos entregables.</p><form id="general-form"><div class="grid2">${field('Nombre profesional','name',state.profile.name||'','text','required maxlength="160"')}${field('Nombre del consultorio','clinic_name',state.profile.clinic_name||'')}</div><div class="grid2">${field('Cédula o identificación profesional','credential',state.profile.credential||'')}${field('Contacto profesional','contact',state.profile.contact||'')}</div><h3>Módulos predeterminados en expedientes nuevos</h3><div class="check-grid">${['Metabolismo','Tiroides','Salud hormonal','Menopausia'].map(m=>`<label class="check"><input type="checkbox" name="module" value="${m}" ${(clinical.default_modules||[]).includes(m)?'checked':''}><span>${m}</span></label>`).join('')}</div><p class="small muted">País clínico: México · Zona horaria: America/Merida.</p><button class="primary" type="submit">Guardar identidad y preferencias</button><div class="form-error" id="general-error"></div></form></section>`;
 if(settingsTab==='clinical')body=`<div class="grid2"><section class="panel"><h2>Barreras obligatorias</h2><div class="policy"><strong>Revisión humana de OCR</strong><span class="tag good">Siempre activa</span><p>Cada resultado extraído queda pendiente hasta cotejar identidad, página, fragmento, valor y unidad.</p></div><div class="policy"><strong>Aprobación del plan</strong><span class="tag good">Siempre activa</span><p>El PDF solo existe después de la revisión clínica y de consistencia del profesional.</p></div><div class="policy"><strong>Sin inferencias silenciosas</strong><span class="tag good">Siempre activa</span><p>Los campos distinguen dato presente, desconocido, no evaluado, no aplicable y ninguno referido.</p></div></section><section class="panel"><h2>Alcance configurado</h2><p class="small muted">Consulta externa de adultos: metabolismo, tiroides, salud hormonal y menopausia. Los módulos seleccionados organizan la evaluación; no asignan diagnósticos.</p><h3>Procesamiento externo</h3><p class="small muted">Cada envío a la API exige confirmación en ese momento. Las imágenes diagnósticas se conservan como originales y no se interpretan en esta versión.</p><h3>Fuentes</h3><p class="small muted">Las fórmulas solo funcionan cuando su fuente ha sido revisada y aprobada por el profesional.</p></section></div>`;
 if(settingsTab==='api')body=`<div class="grid2"><section class="panel"><h2>Proveedor y límites</h2><form id="api-form">${field('Proveedor','provider','OpenAI','text','readonly')}${field('Modelo API','model',state.api.model||'','','placeholder="Ejemplo: modelo contratado"')}${field('Máximo de solicitudes por día','daily_limit',state.api.daily_limit||20,'number','min="1" max="1000" required')}${field('Máximo de resultados por OCR','ocr_field_limit',state.api.ocr_field_limit||150,'number','min="1" max="150" required')}<label class="check"><input type="checkbox" name="enabled" ${state.api.enabled?'checked':''}><span>He revisado las condiciones del proveedor; habilitar únicamente envíos confirmados.</span></label><button class="primary" type="submit">Guardar límites de API</button><div class="form-error" id="api-error"></div></form></section><section class="panel"><h2>Credencial segura</h2><div class="credential-state"><span class="status-dot"></span><strong>${state.api.key_available?'Clave disponible':'Clave pendiente'}</strong></div><p class="small muted">La clave se guarda en el Llavero de macOS. La aplicación solo consulta si existe; nunca la devuelve al navegador, al respaldo ni al registro de auditoría.</p><form id="key-form">${field(state.api.key_available?'Reemplazar clave API':'Clave API','key','','password','required autocomplete="off" placeholder="sk-…"')}<button type="submit">Guardar en el Llavero</button><div class="form-error" id="key-error"></div></form></section></div><section class="panel"><h2>Registro de solicitudes</h2>${ops.length?table(['Fecha','Operación','Estado','Modelo / consumo'],ops.map(o=>`<tr><td>${fmtDate(o.created)}</td><td>${esc(o.type)}</td><td>${status(o.status)}</td><td>${esc(o.model||'—')}<br>${o.usage?esc(JSON.stringify(o.usage)):'Sin consumo disponible'}</td></tr>`)):'<p class="small muted">Todavía no se han realizado solicitudes.</p>'}</section>`;
 if(settingsTab==='documents')body=`<div class="grid2"><section class="panel"><h2>Ingreso de documentos</h2><form id="documents-form">${field('Máximo por archivo (MB)','max_upload_mb',docs.max_upload_mb||15,'number','min="1" max="15" required')}<p class="small muted">Tipos admitidos: PDF, PNG y JPEG. El tipo real se verifica por el contenido del archivo.</p><div class="line"></div><h2>Presentación del PDF</h2>${field('Encabezado del consultorio','pdf_clinic_name',pdf.clinic_name||'Nutrición clínica','text','required')}${field('Línea profesional','professional_line',pdf.professional_line||'')}${area('Introducción para el paciente','patient_intro',pdf.patient_intro||'','maxlength="1000"')}${field('Pie de página','footer',pdf.footer||'')}${field('Color institucional','accent',pdf.accent||'#087e78','color')}<label class="check"><input type="checkbox" name="include_totals" ${pdf.include_totals?'checked':''}><span>Mostrar totales nutricionales documentados por día.</span></label><button class="primary" type="submit">Guardar documentos y PDF</button><div class="form-error" id="documents-error"></div></form></section><section class="panel"><h2>Qué aparece en el PDF</h2><div class="pdf-sample" style="--sample-accent:${esc(pdf.accent||'#087e78')}"><div>${esc((pdf.clinic_name||'Nutrición clínica').toUpperCase())}</div><h2>Plan de alimentación</h2><p>Paciente · versión aprobada · profesional</p><hr><p>${esc(pdf.patient_intro||'Aquí aparecerá la introducción para el paciente.')}</p><small>${esc(pdf.footer||'Pie de página')}</small></div><p class="small muted">La justificación interna permanece excluida del PDF.</p></section></div>`;
 if(settingsTab==='security')body=`<div class="grid2"><section class="panel"><h2>Acceso local</h2><form id="security-form">${field('Duración de nuevas sesiones (horas)','session_hours',security.session_hours||8,'number','min="1" max="12" required')}<button class="primary" type="submit">Guardar duración</button><div class="form-error" id="security-error"></div></form><div class="line"></div><h3>Cambiar contraseña</h3><form id="password-form">${field('Contraseña actual','current','','password','required autocomplete="current-password"')}${field('Nueva contraseña','new','','password','required minlength="12" autocomplete="new-password"')}${field('Repetir nueva contraseña','repeat','','password','required minlength="12" autocomplete="new-password"')}<button type="submit">Cambiar contraseña y cerrar otras sesiones</button><div class="form-error" id="password-error"></div></form></section><section class="panel"><h2>Respaldo cifrado</h2><p class="small muted">Incluye la base de datos y documentos originales. La clave API del Llavero queda excluida.</p><p><strong>Último respaldo:</strong> ${backupCfg.last_created_at?fmtDate(backupCfg.last_created_at):'No registrado'}</p>${button('Crear respaldo ahora','backup','','primary')}<p class="small muted">Frecuencia sugerida: semanal. La descarga se realiza manualmente para asegurar que conserves el archivo y su contraseña.</p></section></div>`;
 if(settingsTab==='system')body=`<div class="cards"><div class="card"><div class="label">Integridad de base</div><div class="value system-value">${d.database_integrity==='ok'?'Correcta':'Revisar'}</div><div class="detail">Verificación ${fmtDate(d.checked_at)}</div></div><div class="card"><div class="label">Registros</div><div class="value">${d.records??0}</div><div class="detail">${d.documents??0} documentos originales</div></div><div class="card"><div class="label">Espacio ocupado</div><div class="value system-value">${d.database_mb??0} MB</div><div class="detail">Documentos: ${d.document_mb??0} MB</div></div></div><section class="panel"><div class="panel-head"><div><h2>Diagnóstico local</h2><p class="small muted">Comprueba integridad, disponibilidad de la credencial y volumen guardado.</p></div>${button('Ejecutar diagnóstico','diagnostics','','primary')}</div>${table(['Componente','Estado'],[['Versión',esc(d.version||state.version)],['Clave API',d.key_available?'Disponible':'Pendiente'],['Carpeta de datos',`<span class="path">${esc(d.data_directory||'')}</span>`]].map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td></tr>`))}<p class="small muted">La aplicación escucha solamente en esta computadora. El cifrado de los archivos en uso depende de FileVault o de la protección del disco.</p></section>`;
 return heading('Centro de configuración','Controla el funcionamiento de la consulta desde un solo lugar.')+`<nav class="settings-tabs" aria-label="Áreas de configuración">${tabs.map(([id,label])=>button(label,'settings-tab',id,settingsTab===id?'active':'')).join('')}</nav>`+body}
function wireView(){if($('patient-search'))$('patient-search').oninput=e=>{const q=e.target.value.toLocaleLowerCase();$('patient-results').innerHTML=patientTable(list('patient').filter(p=>(p.name+' '+p.id).toLocaleLowerCase().includes(q)))};if($('visit-select'))$('visit-select').onchange=e=>{if(!guard()){e.target.value=visitId;return}visitId=e.target.value;render()};const f=$('history-form');if(f){if(currentVisit().status==='closed')f.querySelectorAll('input,select,textarea').forEach(el=>el.disabled=true);f.addEventListener('input',()=>dirty=true);f.onsubmit=async e=>{e.preventDefault();try{let data=new FormData(f),history={};state.fields.forEach(x=>history[x.id]={availability:data.get(x.id+'_availability'),value:data.get(x.id+'_value'),source:data.get(x.id+'_source')});await api('visits/save',{id:visitId,rev:currentVisit().rev,history,assessment:data.get('assessment'),goals:data.get('goals'),next_date:data.get('next_date')});dirty=false;await refresh();toast('Historia guardada con registro de cambios.')}catch(ex){toast(ex.message)}}}
 const bind=(id,path,build,error=id.replace('-form','-error'))=>{const form=$(id);if(!form)return;form.onsubmit=async e=>{e.preventDefault();const data=new FormData(form),button=form.querySelector('button[type=submit]');button.disabled=true;try{await api(path,build(data));await refresh();toast('Configuración guardada con registro de cambios.')}catch(ex){const box=$(error);if(box)box.textContent=ex.message;else toast(ex.message)}finally{button.disabled=false}}};
 bind('general-form','settings/general',f=>({name:f.get('name'),clinic_name:f.get('clinic_name'),credential:f.get('credential'),contact:f.get('contact'),default_modules:f.getAll('module')}));
 bind('api-form','settings/api',f=>({model:f.get('model'),daily_limit:Number(f.get('daily_limit')),ocr_field_limit:Number(f.get('ocr_field_limit')),enabled:f.has('enabled')}));
 bind('key-form','credentials',f=>({key:f.get('key')}));
 bind('documents-form','settings/documents',f=>({max_upload_mb:Number(f.get('max_upload_mb')),pdf_clinic_name:f.get('pdf_clinic_name'),professional_line:f.get('professional_line'),patient_intro:f.get('patient_intro'),footer:f.get('footer'),accent:f.get('accent'),include_totals:f.has('include_totals')}));
 bind('security-form','settings/security',f=>({session_hours:Number(f.get('session_hours'))}));
 bind('password-form','password',f=>{if(f.get('new')!==f.get('repeat'))throw Error('Las contraseñas nuevas no coinciden.');return {current:f.get('current'),new:f.get('new')}},'password-error');
}
function newPatient(){const defaults=state.config?.clinical?.default_modules||[],modules=['Metabolismo','Tiroides','Salud hormonal','Menopausia'];modal('Nuevo expediente',field('Nombre del paciente','name','','text','required maxlength="160"')+`<div class="grid2">${field('Nacimiento (si se conoce)','dob','','date')}${field('Contacto (opcional)','contact')}</div><h3>Áreas de evaluación</h3>`+modules.map(m=>`<label class="check"><input name="module_${m}" type="checkbox" ${defaults.includes(m)?'checked':''}><span>${esc(m)}</span></label>`).join('')+check('Este expediente contiene datos ficticios de prueba','demo'),async f=>{let p=await api('patients',{name:f.get('name'),dob:f.get('dob'),contact:f.get('contact'),modules:modules.filter(m=>f.has('module_'+m)),demo:f.has('demo')});patientId=p.id;visitId='';route='patient';tab='history'},'Crear expediente')}
function newVisit(p){modal('Nueva consulta',field('Fecha de atención','date',dateToday(),'date','required')+select('Tipo','type',['Primera consulta','Seguimiento'])+area('Motivo de consulta','reason','','required'),async f=>{let v=await api('visits',{patient:p,date:f.get('date'),type:f.get('type'),reason:f.get('reason')});patientId=p;visitId=v.id;route='patient';tab='history'},'Abrir consulta')}
function newObservation(){const v=currentVisit();modal('Registrar medición o laboratorio',`<div class="grid2">${field('Nombre exacto del indicador','label','','text','required list="obs-labels"')}<datalist id="obs-labels">${['Peso','Talla','Cintura','Glucosa','Insulina','HbA1c','Colesterol total','LDL-C','HDL-C','Triglicéridos','TSH','T4 libre','T3 libre','Vitamina D 25-OH','Ferritina'].map(x=>`<option value="${x}">`).join('')}</datalist>${select('Tipo de dato','category',[['laboratory','Laboratorio'],['anthropometry','Antropometría'],['clinical','Otro dato clínico']])}</div><div class="grid3">${field('Valor original','value','','text','required')}${field('Unidad exacta','unit','','text','required placeholder="mg/dL, µIU/mL, kg…"')}${field('Fecha de toma o medición','date',v.date,'date','required')}</div><div class="grid2">${field('Límite inferior impreso','reference_low','','number','step="any"')}${field('Límite superior impreso','reference_high','','number','step="any"')}</div>${field('Referencia impresa literal, si no es numérica','reference')}${field('Método, equipo o laboratorio','method','','text','required')}${field('Fuente / documento / quién lo refiere','source','','text','required')}${check('Confirmo el valor, la unidad, la fecha y el origen registrados','confirmed')}`,async f=>{await api('observations',{...Object.fromEntries(f),patient:patientId,visit:visitId,confirmed:f.has('confirmed')})},'Guardar dato')}
function reviewObservation(id){const o=record(id);modal('Revisar · '+o.label,`<p class="small muted">Origen: ${esc(origins[o.origin])} · ${esc(o.source)} · Método: ${esc(o.method)}</p>${o.document?`<p><a href="/api/file/${o.document}" target="_blank" rel="noopener noreferrer">Abrir documento original ↗</a></p>`:''}<div class="grid3">${field('Valor original / corregido','value',o.value,'text','required')}${field('Unidad','unit',o.unit)}${field('Fecha del dato','date',o.date,'date')}</div>${field('Referencia impresa','reference',o.reference)}${o.document?`<div class="grid2">${field('Página','page',o.page)}${field('Fragmento literal de origen','excerpt',o.excerpt)}</div>`:''}${select('Decisión','status',[['approved','Aprobar valor revisado'],['rejected','Rechazar dato']])}${area('Motivo de revisión o corrección','reason','','required')}`,async f=>{await api('observations/review',{...Object.fromEntries(f),id,rev:o.rev})},'Registrar revisión')}
function uploadDoc(){const limit=state.config?.documents?.max_upload_mb||15;modal('Subir estudio',`<label class="field">Archivo original<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg" required></label>${select('Contenido','study_type',['Informe de laboratorio','Informe de composición corporal','Informe de DXA','Informe de ultrasonido','Imagen diagnóstica','Otro informe'])}${field('Fecha del estudio (si consta)','date','','date')}<p class="small muted">El original se guarda localmente. Subirlo no lo envía a una API. Máximo: ${limit} MB.</p>`,async f=>{const file=f.get('file');if(file.size>limit*1024*1024)throw Error(`El máximo configurado es ${limit} MB.`);const encoded=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result.split(',')[1]);r.onerror=rej;r.readAsDataURL(file)});await api('documents',{patient:patientId,visit:visitId,name:file.name,base64:encoded,date:f.get('date'),study_type:f.get('study_type')})},'Guardar original')}
function uploadAudio(){modal('Subir audio de consulta',`<div class="notice info">Usa exclusivamente una grabación ficticia durante esta etapa de pruebas.</div><label class="field">Grabación<input type="file" name="file" accept=".mp3,.m4a,.wav,.ogg,.webm,.flac,.mp4,audio/*" required></label><div class="grid2">${field('Fecha y hora de grabación','recorded_at','','datetime-local')}${field('Conservar hasta (opcional)','retention_until','','date')}</div>${select('Forma de consentimiento','consent_method',[['Consentimiento verbal registrado al inicio del audio','Verbal registrado al inicio del audio'],['Consentimiento escrito conservado por el profesional','Escrito conservado por el profesional'],['Consentimiento verbal y escrito','Verbal y escrito']])}${area('Constancia del consentimiento','consent_statement','La persona fue informada de la grabación, su transcripción mediante un proveedor externo y su uso para documentar esta consulta ficticia.','required minlength="20"')}${check('Confirmo que existe consentimiento explícito y vigente para grabar y transcribir','consent_confirmed')}<p class="small muted">El archivo se guarda en el espacio privado de Supabase. La transcripción se envía a OpenAI y queda pendiente de revisión.</p>`,async f=>{if(!f.has('consent_confirmed'))throw Error('Debes confirmar el consentimiento antes de continuar.');const file=f.get('file');if(!file?.size)throw Error('Selecciona una grabación.');await api('recordings',{patient:patientId,visit:visitId,file,recorded_at:f.get('recorded_at')?new Date(f.get('recorded_at')).toISOString():'',retention_until:f.get('retention_until'),consent_method:f.get('consent_method'),consent_statement:f.get('consent_statement')});toast('Audio guardado y enviado a transcripción.')},'Guardar y transcribir')}
function reviewTranscript(id){const t=record(id);const read=t.status!=='pending_review';modal(read?'Consultar transcripción revisada':'Revisar transcripción',`${area('Texto transcrito','text',t.text||'','required rows="14" '+(read?'readonly':''))}${select('Decisión','status',[['reviewed','Marcar como revisada'],['rejected','Rechazar transcripción']],t.status==='rejected'?'rejected':'reviewed')}${area('Notas de cotejo con el audio','note',t.review_note||'','required minlength="3" '+(read?'readonly':''))}<p class="small muted">Editar el texto registra la versión revisada; no modifica el audio original.</p>`,async f=>{if(read)return;await api('transcripts/review',{id,status:f.get('status'),note:f.get('note'),text:f.get('text')})},read?'Cerrar':'Guardar revisión')}
function identity(id){const d=record(id);modal('Cotejar identidad del estudio',`<p><strong>${esc(d.name)}</strong></p><p>Paciente del expediente: ${esc(record(d.patient)?.name)}</p><p><a href="/api/file/${id}" target="_blank" rel="noopener noreferrer">Consultar original ↗</a></p>${area('Qué datos cotejaste y qué observaste','note',d.identity_note,'required')}${check('Confirmo que el documento corresponde a este paciente','confirmed')}`,async f=>{await api('documents/identity',{id,rev:d.rev,note:f.get('note'),confirmed:f.has('confirmed')})},'Registrar cotejo')}
function ocr(id){const d=record(id);modal('Extraer resultados por API',`<p>Se enviará <strong>${esc(d.name)}</strong> a OpenAI para extraer su texto y resultados. La API puede procesar datos identificativos presentes en el original.</p><p class="small muted">La extracción se guardará como pendiente. No se interpretarán imágenes diagnósticas.</p>${check('He revisado el documento y autorizo este envío al proveedor configurado','send_confirmed')}`,async f=>{await api('documents/ocr',{id,send_confirmed:f.has('send_confirmed')});toast('Extracción guardada. Revisa cada resultado.');patientId=d.patient;visitId=d.visit;route='patient';tab='observations'},'Enviar y extraer')}
function calculateModal(){const obs=list('observation',patientId).filter(o=>o.status==='approved');const choices=label=>[['','Selecciona una observación'],...obs.filter(o=>o.label===label).map(o=>[o.id,`${o.value} ${o.unit} · ${fmtDate(o.date)} · ${o.method}`])];modal('Cálculo reproducible',select('Método','formula',[['bmi','IMC'],['mifflin','Mifflin–St Jeor · gasto en reposo']])+`<div class="grid2">${select('Peso validado (kg)','weight',choices('Peso'))}${select('Talla validada (cm)','height',choices('Talla'))}</div>${field('Justificación si las fechas difieren','date_reason')}<details class="module"><summary>Entradas adicionales para Mifflin–St Jeor</summary><div class="module-body"><div class="grid2">${field('Edad en la fecha de valoración','age','','number','min="19" max="78"')}${select('Codificación de sexo en esta ecuación','sex',[['','Seleccionar'],['female','Femenino · coeficiente −161'],['male','Masculino · coeficiente +5']])}</div>${field('Fuente y fecha de la edad','age_source')}${check('Revisé la aplicabilidad de esta ecuación en esta persona','applicability')}</div></details>`,async f=>{await api('calculations',{...Object.fromEntries(f),patient:patientId,visit:visitId,applicability:f.has('applicability')})},'Calcular y guardar')}
function aiModal(){modal('Solicitar borrador de IA',area('Qué necesitas preparar','task','','required placeholder="Ejemplo: organiza los datos revisados y enumera qué falta para valorar el plan"')+`<p class="small muted">Se enviarán la historia de esta consulta, las observaciones aprobadas y las fichas de las fuentes activas a OpenAI. No se incluyen automáticamente nombre ni contacto; el texto libre puede contenerlos.</p>${check('Revisé el contexto de esta consulta y autorizo su envío al proveedor','send_confirmed')}`,async f=>{await api('ai',{patient:patientId,visit:visitId,task:f.get('task'),send_confirmed:f.has('send_confirmed')})},'Generar borrador')}
function reviewSource(id){const s=record(id);modal('Revisión de fuente',`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></p><p>${esc(s.scope)}</p>${area('Fundamento de tu decisión y límites de aplicación','note',s.review_note||'','required')}${check('Revisé esta fuente y apruebo su uso en el módulo descrito','approved')}`,async f=>{await api('sources/review',{id,rev:s.rev,note:f.get('note'),approved:f.has('approved')})},'Guardar revisión')}
function editPlan(id){const p=record(id)||{title:'Plan de alimentación',items:[],objective:currentVisit()?.goals||'',target_kcal:'',recommendations:'',supplements:'',internal_notes:''};let items=JSON.parse(JSON.stringify(p.items));modal(p.id?'Editar borrador':'Nuevo plan',field('Título','title',p.title,'text','required')+`<div class="grid2">${field('Objetivo energético prescrito (opcional)','target_kcal',p.target_kcal??'','number','min="1" step="any"')}${field('Suplementación indicada o ninguna','supplements',p.supplements)}</div>${area('Objetivos de la intervención','objective',p.objective,'required')}<div class="line"></div><h3>Preparaciones</h3><div id="items-editor"></div><button type="button" id="add-item">＋ Añadir preparación</button><div class="line"></div>${area('Recomendaciones para el paciente','recommendations',p.recommendations)}${area('Justificación interna (no aparece en PDF)','internal_notes',p.internal_notes)}`,async(f,form)=>{syncItems();await api('plans',{...Object.fromEntries(f),id:p.id,rev:p.rev,patient:p.patient||patientId,visit:p.visit||visitId,items})},'Guardar borrador');
 function syncItems(){items=[...$('items-editor').querySelectorAll('[data-item]')].map(row=>{let get=n=>row.querySelector(`[data-key="${n}"]`).value;return {components:[...row.querySelectorAll('[data-component]')].map(c=>({food:c.querySelector('select').value,grams:c.querySelector('input').value})).filter(c=>c.food),day:Number(get('day')),meal:get('meal'),title:get('title'),ingredients:get('ingredients'),instructions:get('instructions'),nutrition_source:get('nutrition_source'),nutrients:Object.fromEntries(['kcal','protein','carbs','fat'].map(k=>[k,get(k)===''?null:Number(get(k))]))}})}
 function rowField(label,key,value,type='text'){return `<label class="field">${label}<input data-key="${key}" type="${type}" value="${esc(value??'')}" ${type==='number'?'min="0" step="any"':''}></label>`}
 function componentRow(c){return `<div class="toolbar" data-component><label class="field">Alimento<select>${options([['','Seleccionar'],...list('food').map(f=>[f.id,f.name+' · '+f.state])],c.food)}</select></label><label class="field">Gramos<input type="number" min="0.01" step="any" value="${esc(c.grams)}"></label><button type="button" data-remove-component>Quitar</button></div>`}
 function renderItems(){$('items-editor').innerHTML=items.map((i,index)=>`<details class="module" open><summary>Preparación ${index+1} · ${esc(i.title||'Sin título')}</summary><div class="module-body"><div class="grid3"><label class="field">Día<select data-key="day">${options(days.map((d,n)=>[n,d]),i.day)}</select></label><label class="field">Tiempo<select data-key="meal">${options(['Desayuno','Colación 1','Comida','Colación 2','Cena'],i.meal)}</select></label>${rowField('Platillo','title',i.title)}</div><div data-item="${index}" class="item-fields"></div></div></details>`).join('');
 // Keep all preparation controls under one wrapper to read them consistently.
 $('items-editor').querySelectorAll('.module').forEach((d,index)=>{let i=items[index];const body=d.querySelector('.module-body');body.dataset.item=index;d.querySelector('.item-fields').remove();body.insertAdjacentHTML('beforeend',`<div class="component-list">${(i.components||[]).map(c=>componentRow(c)).join('')}</div><button type="button" data-add-component="${index}">＋ Ingrediente del catálogo</button><p class="tiny muted">Si seleccionas ingredientes del catálogo, se calculan sus nutrientes desde gramos y composición por 100 g. Las cantidades y fuentes quedan guardadas con el plan.</p><label class="field">Ingredientes y cantidades, indicando crudo/cocido<textarea data-key="ingredients">${esc(i.ingredients||'')}</textarea></label><label class="field">Preparación<textarea data-key="instructions">${esc(i.instructions||'')}</textarea></label><details><summary class="small">Composición documentada de esta preparación</summary><p class="tiny muted">Valores totales de esta preparación, capturados desde una fuente que puedas verificar. Vacío significa no determinado, nunca cero. Si usas el catálogo, el sistema sustituye estos valores por el cálculo de sus ingredientes al guardar.</p><div class="grid2">${rowField('Energía (kcal)','kcal',i.nutrients?.kcal,'number')}${rowField('Proteína (g)','protein',i.nutrients?.protein,'number')}${rowField('Hidratos (g)','carbs',i.nutrients?.carbs,'number')}${rowField('Grasa (g)','fat',i.nutrients?.fat,'number')}</div>${rowField('Fuente y método de la composición','nutrition_source',i.nutrition_source)}</details><button type="button" data-remove-item="${index}" class="danger">Quitar preparación</button>`)});
 $('items-editor').querySelectorAll('[data-add-component]').forEach(b=>b.onclick=()=>{syncItems();items[Number(b.dataset.addComponent)].components??=[];items[Number(b.dataset.addComponent)].components.push({food:'',grams:''});renderItems()}); $('items-editor').querySelectorAll('[data-remove-component]').forEach(b=>b.onclick=()=>b.closest('[data-component]').remove()); $('items-editor').querySelectorAll('[data-remove-item]').forEach(b=>b.onclick=()=>{syncItems();items.splice(Number(b.dataset.removeItem),1);renderItems()})}
 $('add-item').onclick=()=>{syncItems();items.push({day:0,meal:'Desayuno',title:'',ingredients:'',instructions:'',nutrition_source:'',nutrients:{}});renderItems()};renderItems();
}
function approvePlan(id){const p=record(id);modal('Aprobar versión del plan',`<p><strong>${esc(p.title)} · v${p.version}</strong></p><p class="small muted">La aprobación conserva los datos de referencia y habilita el PDF. Una edición posterior se hace en una nueva versión.</p>${check('Revisé historia, alergias, restricciones, medicamentos y suplementos','clinical_review')}${check('Revisé ingredientes, cantidades y coherencia entre objetivos y plan','consistency_review')}${check('Si hay totales incompletos, acepto que se indiquen explícitamente en el PDF','incomplete_ack')}${area('Justificación de aprobación / desviaciones aceptadas','review_note','','required')}`,async f=>{await api('plans/approve',{id,rev:p.rev,clinical_review:f.has('clinical_review'),consistency_review:f.has('consistency_review'),incomplete_ack:f.has('incomplete_ack'),review_note:f.get('review_note')})},'Aprobar y habilitar PDF')}
function previewPlan(id){const p=record(id),tot=planTotals(p);readonlyModal(p.title,`<div class="tags">${status(p.status)}<span class="tag">v${p.version}</span></div><p>${esc(p.objective)}</p>${days.map((d,n)=>{let items=p.items.filter(i=>i.day===n);return items.length?`<h3 class="day-heading">${d}</h3>${items.map(i=>`<div class="entry"><strong>${esc(i.meal)} · ${esc(i.title)}</strong><p>${esc(i.ingredients)}</p><p class="small muted">${esc(i.instructions)}</p></div>`).join('')}<p class="small muted">${tot[n].complete?`${tot[n].kcal.toFixed(1)} kcal · P ${tot[n].protein.toFixed(1)} g · HC ${tot[n].carbs.toFixed(1)} g · G ${tot[n].fat.toFixed(1)} g`:'Totales incompletos'}</p>`:''}).join('')}<h3>Recomendaciones</h3><p class="pre">${esc(p.recommendations)}</p><h3>Suplementación</h3><p class="pre">${esc(p.supplements||'No registrada')}</p><details class="module"><summary>Justificación interna · no se entrega al paciente</summary><div class="module-body pre">${esc(p.internal_notes||'No registrada')}</div></details>`)}
function backup(){modal('Descargar respaldo cifrado',`<p>Incluye expedientes, historial y documentos originales. Guarda la contraseña por separado; será necesaria para restaurar.</p>${field('Contraseña del respaldo','password','','password','required minlength="12" autocomplete="new-password"')}${field('Repite la contraseña','repeat','','password','required minlength="12" autocomplete="new-password"')}`,async f=>{if(f.get('password')!==f.get('repeat'))throw Error('Las contraseñas no coinciden.');const blob=await api('backup',{password:f.get('password')},true);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nutricion-'+dateToday()+'.nutribak';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Respaldo cifrado descargado.')},'Crear y descargar')}
async function handle(action,id){
 if(action==='route'){if(!guard())return;route=id;render()}
 else if(action==='settings-tab'){settingsTab=id;render()}
 else if(action==='diagnostics'){await api('diagnostics/check',{});await refresh();toast('Diagnóstico local completado.')}
 else if(action==='boot')await boot();
 else if(action==='logout'){if(!guard())return;await api('logout',{});await boot()}
 else if(action==='close-modal')$('modal').close();
 else if(action==='new-patient')newPatient();
 else if(action==='open-patient'){if(!guard())return;patientId=id;visitId=list('visit',id)[0]?.id||'';route='patient';tab='history';render()}
 else if(action==='new-visit'){if(!guard())return;newVisit(id)}
 else if(action==='patient-tab'){if(!guard())return;tab=id;render()}
 else if(action==='new-observation')newObservation();
 else if(action==='review-observation')reviewObservation(id);
 else if(action==='upload')uploadDoc();
 else if(action==='upload-audio')uploadAudio();
 else if(action==='review-transcript')reviewTranscript(id);
 else if(action==='identity')identity(id);
 else if(action==='ocr')ocr(id);
 else if(action==='calculate')calculateModal();
 else if(action==='ai')aiModal();
 else if(action==='review-source')reviewSource(id);
 else if(action==='new-food')newFood();
 else if(action==='new-source')newSource();
 else if(action==='new-plan')editPlan();
 else if(action==='edit-plan')editPlan(id);
 else if(action==='approve-plan')approvePlan(id);
 else if(action==='preview-plan')previewPlan(id);
 else if(action==='backup')backup();
 else if(action==='calc-detail'){let c=record(id);readonlyModal('Entradas y fuente del cálculo',`<p class="metric-value">${esc(c.value)} ${esc(c.unit)}</p><p>${esc(c.source_snapshot.formula)}</p><pre>${esc(JSON.stringify(c.inputs,null,2))}</pre><a href="${esc(c.source_snapshot.url)}" target="_blank" rel="noopener noreferrer">Abrir fuente ↗</a><p class="small muted">${c.stale?'Las entradas cambiaron. Este resultado conserva la versión anterior.':'Entradas vigentes.'}</p>`)}
 else if(action==='open-document'){let d=record(id);if(state.cloud){const url=await api('file/'+id);window.open(url,'_blank','noopener,noreferrer')}else readonlyModal(d.name,`<a href="/api/file/${id}" target="_blank" rel="noopener noreferrer">Abrir original en otra pestaña ↗</a><p class="small muted">Integridad SHA-256: ${esc(d.sha256)}</p>${d.mime==='application/pdf'?`<iframe class="doc-preview" title="Informe original" src="/api/file/${id}"></iframe>`:`<div class="doc-preview"><img src="/api/file/${id}" alt="Documento original"></div>`}`)}
 else if(action==='audit'){let r=record(id),events=await api('audit/'+id);readonlyModal('Trazabilidad del registro',`<p class="small muted">${esc(r?.label||r?.name||r?.title||r?.reason||id)}</p>${events.map(ev=>`<div class="entry"><strong>${esc(ev.reason)}</strong><p class="small muted">${esc(ev.actor)} · ${esc(ev.at)}</p><details><summary class="small">Datos de esta versión</summary><pre>${esc(JSON.stringify(JSON.parse(ev.after_json),null,2))}</pre></details></div>`).join('')}`)}
 else if(action==='close-visit'){if(dirty){toast('Guarda la historia antes de cerrar la consulta.');return}let v=record(id);modal('Cerrar consulta',`<p>Se conservará la historia de esta consulta. Para continuar el seguimiento crearás una nueva consulta.</p>${check('Revisé la valoración y deseo cerrar esta consulta','confirmed')}`,async f=>{if(!f.has('confirmed'))throw Error('Confirma el cierre.');await api('visits/close',{id,rev:v.rev})},'Cerrar consulta')}
 else if(action==='clone-plan'){let p=record(id),vs=list('visit',p.patient).filter(v=>v.status==='draft');modal('Crear nueva versión',select('Consulta destino','visit',vs.map(v=>[v.id,fmtDate(v.date)+' · '+v.reason]))+area('Motivo del ajuste','reason','','required'),async f=>{await api('plans/clone',{id,visit:f.get('visit'),reason:f.get('reason')})},'Crear borrador')}
 else if(action==='review-proposal'){let p=record(id);modal('Revisar propuesta de IA',`<p>Confirma que la evidencia respalda el texto y su pertinencia en esta consulta. La aprobación no cambia el plan automáticamente.</p>${area('Resultado de revisión','note','','required')}${check('Apruebo esta propuesta revisada; sin marcar se registra rechazada','approved')}`,async f=>{await api('proposals/review',{id,rev:p.rev,note:f.get('note'),approved:f.has('approved')})},'Guardar revisión')}
}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action]');if(!b)return;try{await handle(b.dataset.action,b.dataset.id)}catch(ex){toast(ex.message)}});
boot();
})();
